title = "ECHO RESONANCE Paper 1 - data description"
authors = ["Kevin S. Bonham", "Vanja Klepac-Ceraj"]
description = "This file contains machine-readable information about data files used in these notebooks. Wherever possible, these data are in publically accessible locations, though some data are sensitive and are therefore restricted."

[filepaths]
read_counts = "/babbage/echo/profiles/functional"
taxonomic_profiles = "/babbage/echo/profiles/taxonomic"
functional_profiles = "/babbage/echo/profiles/functional"

[tables] # relative to `data/metadata`
clinical_metadata="clinical.csv"
sample_metadata="samples.csv"
joined_metadata="joined.csv"
