kos = widen2comm(functional_profiles(kind="kos_names_relab")..., featurecol=:func)
kos = view(kos, species=map(x-> !in(x, ("UNMAPPED", "UNGROUPED")), featurenames(kos)))
stratkos = widen2comm(functional_profiles(kind="kos_names_relab", stratified=true)..., featurecol=:func)
stratkos = view(stratkos, species=map(x-> !in(x, ("UNMAPPED", "UNGROUPED")), featurenames(stratkos)))
pfams = widen2comm(functional_profiles(kind="pfams_names_relab")..., featurecol=:func)
pfams = view(pfams, species=map(x-> !in(x, ("UNMAPPED", "UNGROUPED")), featurenames(pfams)))
ecs = widen2comm(functional_profiles(kind="ecs_names_relab")..., featurecol=:func)
ecs = view(ecs, species=map(x-> !in(x, ("UNMAPPED", "UNGROUPED")), featurenames(ecs)))
